plugins { id 'com.android.application' }

android {
    namespace 'com.interfaz.hudnavigation'
    compileSdk 35
    defaultConfig {
        applicationId 'com.interfaz.hudnavigation'
        minSdk 23
        targetSdk 35
        versionCode 31
        versionName '31'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
